# Generated by Django 3.0 on 2020-06-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=20, verbose_name='单号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('system', models.IntegerField(choices=[('1', 'PaaS'), ('2', '收单'), ('3', '互联网'), ('4', '金盈信'), ('5', '风控'), ('6', '反洗钱')], default='PaaS', verbose_name='系统')),
                ('typ', models.IntegerField(choices=[('1', '数据执行'), ('2', '数据提取')], default=1, verbose_name='类型')),
                ('content', models.TextField(max_length=200, verbose_name='内容')),
                ('sender', models.TextField(max_length=20, verbose_name='发送人')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('auditors', models.TextField(max_length=20, verbose_name='审核人')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('handler', models.TextField(blank=True, max_length=20, null=True, verbose_name='处理人')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('status', models.IntegerField(choices=[('1', '未提交'), ('2', '未审核'), ('3', '审核一通过'), ('4', '审核二通过'), ('5', '已执行'), ('6', '已驳回')], verbose_name='工单状态')),
                ('comment', models.TextField(max_length=200, verbose_name='说明')),
            ],
        ),
    ]
