# Generated by Django 3.0 on 2020-06-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200613_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[('1', '未提交'), ('2', '未审核'), ('3', '审核一通过'), ('4', '审核二通过'), ('5', '已执行'), ('6', '已驳回')], default=1, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='system',
            field=models.IntegerField(choices=[('1', 'PaaS'), ('2', '收单'), ('3', '互联网'), ('4', '金盈信'), ('5', '风控'), ('6', '反洗钱')], default=1, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='typ',
            field=models.IntegerField(choices=[('1', '数据执行'), ('2', '数据提取')], default=1, verbose_name='类型'),
        ),
    ]
