# Generated by Django 3.0 on 2020-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200613_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': '工单表', 'verbose_name_plural': '工单表'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='auditors',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='审核人'),
        ),
    ]
