# Generated by Django 3.0 on 2020-06-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20200613_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='auditors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='handler',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(max_length=50, verbose_name='单号'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='发送人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, '未提交'), (2, '待审核'), (3, '审核一通过'), (4, '审核二通过'), (5, '已执行'), (6, '已驳回')], verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
