# Generated by Django 3.0 on 2020-06-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20200617_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='说明'),
        ),
    ]
